### ISSUE TITLE
CoreDNS will not compile when using the ads plugin

### ISSUE THREAD

**Issue by cbuijs** [c-mueller/ads#18]
Hi,

First: Thanks for this very cool plugin! Keep up the good work!

But...

When following the instructions to add the plugin and compile coredns, following errors occurr during the make:

```
# github.com/c-mueller/ads
coredns/go/src/github.com/c-mueller/ads/setup.go:51:24: cannot use c (type *"github.com/mholt/caddy".Controller) as type *"github.com/caddyserver/caddy".Controller in argument to metrics.MustRegister
coredns/go/src/github.com/c-mueller/ads/setup.go:52:24: cannot use c (type *"github.com/mholt/caddy".Controller) as type *"github.com/caddyserver/caddy".Controller in argument to metrics.MustRegister
coredns/go/src/github.com/c-mueller/ads/setup.go:53:24: cannot use c (type *"github.com/mholt/caddy".Controller) as type *"github.com/caddyserver/caddy".Controller in argument to metrics.MustRegister
coredns/go/src/github.com/c-mueller/ads/setup.go:54:24: cannot use c (type *"github.com/mholt/caddy".Controller) as type *"github.com/caddyserver/caddy".Controller in argument to metrics.MustRegister
coredns/go/src/github.com/c-mueller/ads/setup.go:67:21: cannot use c (type *"github.com/mholt/caddy".Controller) as type *"github.com/caddyserver/caddy".Controller in argument to dnsserver.GetConfig

```

I see this with many "external" plugins and I think something changed at one point with the go modules and they are always related to Caddy.

Could you provide info/documentation how to succesfull compile? E.g. how do you do it? Using the latest coredns v1.5.2 and go version go1.12.7 linux/amd64.

Cheers,
-Chris.

**Comment by c-mueller** [comment]
Hey,
thanks for your submission. The problem should be "fixed" it was just a matter of replacing the "github.com/mholt/caddy" with "github.com/caddyserver/caddy". They have updated to Caddy 1.0.1 introducing this issue: https://github.com/coredns/coredns/pull/2961

The problem now is "go modules" which always wants to grab the latest tag.  Making the deveopment very painful. I'm sure there is a fix for that I just haven't stumbled upon it.

**Comment by cbuijs** [comment]
No worries.

I found an intermediate fix:

```
mkdir -p ~/go/src/github.com/mholt
ln -sd ~/go/src/github.com/caddyserver/caddy ~/go/src/github.com/mholt/caddy
```

Before doing all go get's and builds etc.

Not sure if it breaks something but so-far so-good :-).

**Comment by cbuijs** [comment]
After your last update correcting the caddy paths, all is great again! Thanks!
