### ISSUE TITLE
ads,会不断的重读,并且读不出列表个数!

### ISSUE THREAD

**Issue by snakwu** [c-mueller/ads#33]
Apr 18 08:30:21 dns_server rc.local[1012]: [INFO] plugin/ads: Updating lists from Local files...
Apr 18 08:30:21 dns_server rc.local[1012]: [INFO] plugin/ads: [File Update] Loaded 0 entries into Blacklist and 1 entries into whitelist
Apr 18 08:31:21 dns_server rc.local[1012]: [INFO] plugin/ads: Updating lists from Local files...
Apr 18 08:31:21 dns_server rc.local[1012]: [INFO] plugin/ads: [File Update] Loaded 0 entries into Blacklist and 1 entries into whitelist

这是我的配置:

    ads {
        blacklist https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt
        whitelist file:///home/snakwu/CoreDNS/whitelist.txt
        auto-update-interval 24h
        list-store /home/snakwu/CoreDNS/ads-cache
        }

**Comment by snakwu** [comment]
打开网页非常慢！！

**Comment by c-mueller** [comment]
Hey, 
Thanks for your issue submission. Could you please provide a more detailed english description of your problem. Unfortunately i do not understand what excatly the problem is, since I cannot speak chinese and The translation tools do not provide enough information to find out what the problem is.

**Comment by snakwu** [comment]
> Hey, 
> Thanks for your issue submission. Could you please provide a more detailed english description of your problem. Unfortunately i do not understand what excatly the problem is, since I cannot speak chinese and The translation tools do not provide enough information to find out what the problem is.

After adding the ads plugin, opening the webpage becomes very slow

**Comment by c-mueller** [comment]
Which webpage? Anyone?

**Comment by snakwu** [comment]
是的打开所有网页都非常慢,whitelist 只有一个域名

> Which webpage? Anyone?
> 
> Could you also tell me the true length in lines of your whitelist file, by looking at a different tool like `wc -l` or a text editor.

是的,所有网页都非常慢,我的白名单里只有一个域!

**Comment by snakwu** [comment]
> Which webpage? Anyone?
> 
> Could you also tell me the true length in lines of your whitelist file, by looking at a different tool like `wc -l` or a text editor.

I added the ads plugin to coredns to make, and then, opening all web pages became very slow ...

**Comment by c-mueller** [comment]
I am not aware of such a problem, since the internal Datastructure used should not really reduce performance, especially not if you only have ~40k entries in your blacklist. I will take a look at it and get back to you asap.

**Comment by c-mueller** [comment]
One more question: Do you use any other, out of tree, plugins?

**Comment by snakwu** [comment]
> One more question: Do you use any other, out of tree, plugins?

. {                                                                                    
   ads {
    blacklist https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt
    whitelist file:///home/snakwu/CoreDNS/whitelist.txt
    auto-update-interval 24h
    list-store /home/snakwu/CoreDNS/ads-cache
    }
       fanout . 127.0.0.1:5301 127.0.0.1:5302 127.0.0.1:5303 {                            
       except 0-100.com 0-6.com 0-gold.net 00.net 00000wg.com 0000go.com 00042.com 000 ..................
    }                                                                                  
    forward . 127.0.0.1:5304                                                           
    cache                                                                              
    health                                                                             
    reload 10s                                                                         
}                                                                                      
.:5301 {                                                                               
    forward . tls://8.8.8.8 tls://8.8.4.4 {                                            
        tls_servername dns.google                                                      
    }                                                                                  
}                                                                                      
.:5302 {                                                                               
    forward . tls://9.9.9.9 tls://9.9.9.10 {                                           
        tls_servername dns.quad9.net                                                   
    }                                                                                  
}                                                                                      
.:5303 {                                                                               
    forward . tls://1.1.1.1 tls://1.0.0.1 {                                            
        tls_servername cloudflare-dns.com                                              
    }                                                                                  
}                                                                                      
.:5304 {                                                                               
    fanout . 202.96.128.86 202.96.134.33 223.5.5.5 119.29.29.29 114.114.114.114        
}                                                                                      
.:5344 {                                                                               
    fanout . 127.0.0.1:5301 127.0.0.1:5302 127.0.0.1:5303                              
    template IN AAAA .                                                                 
}

**Comment by c-mueller** [comment]
Alright, I honestly cannot reproduce the issue. I tired, as you can see below, however the resolution times do not slow down, meaurably in my tests using the ads plugin. Maybe you can try reproducing what i did using `dig`. 

The test Corefile
```
.:5354 {
	ads {
	    blacklist https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt
	    whitelist file:///home/chris/Downloads/whitelist.txt
	    auto-update-interval 24h
	    list-store ads-cache.json.gz
	 }
	forward . 1.1.1.1
	log
	errors
}
```
Log output with ads enabled:
![image](https://user-images.githubusercontent.com/2706976/79643880-7faf4000-81a5-11ea-99c9-9d467d386961.png)

With `ads` enabled:
![image](https://user-images.githubusercontent.com/2706976/79643823-1d563f80-81a5-11ea-88e9-4ebad1ad1f5e.png)
![image](https://user-images.githubusercontent.com/2706976/79643920-c43adb80-81a5-11ea-9dd2-d568c1432e99.png)

With `ads` disabled:
![image](https://user-images.githubusercontent.com/2706976/79643967-1bd94700-81a6-11ea-80b9-e24c7a18b031.png)
![image](https://user-images.githubusercontent.com/2706976/79643956-03692c80-81a6-11ea-8632-389c4a32b9eb.png)

**Comment by snakwu** [comment]
> Alright, I honestly cannot reproduce the issue. I tired, as you can see below, however the resolution times do not slow down, meaurably in my tests using the ads plugin. Maybe you can try reproducing what i did using `dig`. 
> 
> The test Corefile
> ```
> .:5354 {
> 	ads {
> 	    blacklist https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt
> 	    whitelist file:///home/chris/Downloads/whitelist.txt
> 	    auto-update-interval 24h
> 	    list-store ads-cache.json.gz
> 	 }
> 	forward . 1.1.1.1
> 	log
> 	errors
> }
> ```
> Log output with ads enabled:
> ![image](https://user-images.githubusercontent.com/2706976/79643880-7faf4000-81a5-11ea-99c9-9d467d386961.png)
> 
> With `ads` enabled:
> ![image](https://user-images.githubusercontent.com/2706976/79643823-1d563f80-81a5-11ea-88e9-4ebad1ad1f5e.png)
> ![image](https://user-images.githubusercontent.com/2706976/79643920-c43adb80-81a5-11ea-9dd2-d568c1432e99.png)
> 
> With `ads` disabled:
> ![image](https://user-images.githubusercontent.com/2706976/79643967-1bd94700-81a6-11ea-80b9-e24c7a18b031.png)
> ![image](https://user-images.githubusercontent.com/2706976/79643956-03692c80-81a6-11ea-8632-389c4a32b9eb.png)
> 
> 

The query result is delayed. I have seen it is normal and there is no problem. It is estimated that some css,js links are blocked, resulting in the whole web page stuck.

**Comment by snakwu** [comment]
![image](https://user-images.githubusercontent.com/5343595/79685456-86a08600-826b-11ea-8228-063c6dee7520.png)



Opening the webpage is very slow, especially with some video ads, and these ads cannot be deleted!

**Comment by snakwu** [comment]
@c-mueller system：ubuntu server 18.04

**Comment by c-mueller** [comment]
I am sorry, I  have absolutely no idea what causes this problem, however i am pretty sure it is not the fault of the `ads` plugin. Why? Mainly because 
1. i am unable to reproduce your issues
2. I have used the `ads` plugin with blacklists of approx 500k blacklisted domains, without a measurable performance impact.
   - An Exception to this might be many ( >1000) Regex rules, since every qname has to be validated with every regex rule, However normal Black and whitelists use a string to bool map to perfom the block lookup making it very fast.
3. Loading times might increase if qnames get blocked, however this can be considered intended behaviour and should also occur, wehn using a different DNS blocking software like PiHole.
