### ISSUE TITLE
Support CoreDNS 1.8

### ISSUE THREAD

**Issue by jplot** [c-mueller/ads#45]
Is it possible to make a release with the last changes to be compatible with version 1.8 of coredns?

**Comment by c-mueller** [comment]
Hey there,
i will look into that in the next days. Unfortunately i missed this release.

Thank you.

**Comment by c-mueller** [comment]
Just a small correction: I fixed it real quick, since it did not need any code changes. Release `v0.2.5` should be available soon.

Please report any bugs that might appear, since i was not able to test the plugin just yet.
