### ISSUE TITLE
[DRAFT] Consider adding a API

### ISSUE THREAD

**Issue by c-mueller** [c-mueller/ads#5]
To get some statistics or block websites that are not on a blocklist some sort of HTTP API might be useful.

One huge foucs here should be simlicity to keep the functionality very simple:

Some notes on the functionality and mappings:
Authentication using basic auth

**Mappings**:
- `GET /api/stats` -> show PiHole llike stats of the last 24h
- `GET /api/Blocklists` -> Return a list of the blocklists currently used (including manually added ones and regex)
- `GET /api/blocklists/:name` -> Get the specific blocklists contents
- `POST /api/blocklist/regex/add` -> Add A Regex to block
- `POST /api/blocklist/regex/delete` -> Delete A Regex to block

**Comment by dichro** [comment]
Another possibility is to do all of the stats externally, to keep this plugin as light as possible. For example, one could use the dnstap plugin to log these requests, and then build a stats dashboard based on the real-time dnstap data.

**Comment by c-mueller** [comment]
First of all: Thanks for your suggestion!

Getting rid of the stats thing is probably a good idea. Thats why i have removed the code I already wrote in the `master` branch.
I will still consider some way to dynamically configure Block rules, however I am not sure how at the moment.

**Comment by adrianrudnik** [comment]
It's not a bad idea, but not sure if its worth the effort. Pretty common is an exporter for Prometheus, writte like https://prometheus.io/docs/instrumenting/writing_exporters/ and also available for coredns itself https://github.com/coredns/coredns/tree/master/plugin/metrics

**Comment by dichro** [comment]
Prometheus is great for simple metrics, like counting how many lookups were blocked vs allowed, but it doesn't do well with high-cardinality metrics, like tracking how many times each specific blocked domain has had a lookup blocked, or what are the top blocked domains. Though perhaps richer stats like that aren't sufficiently interesting to bother with.

**Comment by c-mueller** [comment]
At this point I want to note that the plugin already exposes (at least it should) some metrics through prometheus:
https://github.com/c-mueller/ads/blob/master/metrics.go

**Comment by c-mueller** [comment]
Because I think that the prometheus stats expose enough information. I will not further consider the implementation of this part of the api.

Regarding the dynamic configuration of rules I think going the same route as the `hosts` plugin is the best solution. This means that Rules can be dynamically configured through a external file. where the path gets defined in the Corefile. This file gets reloaded in a certan interval (or maybe through filesystem hooks).

I will open a new issue for this. This one is closed!
