### ISSUE TITLE
Implement whitelist feature

### ISSUE THREAD

**Issue by rox-wolf** [c-mueller/ads#6]
First of all, very nice project! I have replaced my pihole with coredns+ads. So now I have names for my network and ad blocking. And it's a bit faster than pihole, I did few benchmarks using DNSBench. So it servers names and blocks ads yet it's faster than pihole, which only blocks ads.

Currently whitelist would be very good feature as many of the blocklists are quite aggressive and I can't exclude names I was able on pihole.

**Comment by c-mueller** [comment]
Thank you for your suggestion!
I have implemented this feature in the latest commit eecd3becc692ac8a4cfc87b235a631fc2d778833.
It is now possible to manually white- and blacklist qnames from within the Corefile.
The following code sample shows how. I think this does not need further explanation.
```
ads {
  whitelist <QNAME>
  blacklist <QNAME>
  whitelist-regex <QNAME-REGEX>
  blacklist-regex <QNAME-REGEX>
}
```
